version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1
    container_name: mysql-db
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql

#  composer:
#    image: composer:2
#    container_name: composer
#    working_dir: /var/www/html
#    volumes:
#      - ./src:/var/www/html
#    command: ["install", "--no-scripts"]

volumes:
  mysql_data: